---
base_url:
  description: Cleve base URL.
  type: string
  required: true

illumina_directories:
  description: Root directory in which to look for new sequencing runs
  type: array
  required: true
  minLength: 1
  items:
    type: string

api_key:
  description: Cleve API key
  type: string
  required: true
  secret: true

required_files:
  description: Files that are required in a run directory for it to be considered by the sensor
  type: array
  required: true
  minLength: 1
  items:
    type: string
  default:
    - RunInfo.xml
    - RunParameters.xml

exclude_marker:
  description: Name of a file that indicates that a run directory should be excluded by the sensor
  type: string
  required: true
  default: .cleve_exclude
