name: linting

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: astral-sh/ruff@4
